# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\jarvisqtUIcopy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvisui(object):
    def setupUi(self, jarvisui):
        jarvisui.setObjectName("jarvisui")
        jarvisui.resize(1920, 1080)
        self.label = QtWidgets.QLabel(jarvisui)
        self.label.setGeometry(QtCore.QRect(-20, -80, 2181, 1231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\black.png"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(jarvisui)
        self.label_3.setGeometry(QtCore.QRect(510, 200, 571, 861))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\download.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(jarvisui)
        self.label_2.setGeometry(QtCore.QRect(1560, -30, 341, 401))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\212f727d1a5f117947db9a7403a4f7aa.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(jarvisui)
        self.label_4.setGeometry(QtCore.QRect(0, -70, 491, 251))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\T8bahf.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(jarvisui)
        self.label_5.setGeometry(QtCore.QRect(1060, 330, 311, 251))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\9e759fd37ccd98da121b670249f34afa.gif"))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(jarvisui)
        self.label_7.setGeometry(QtCore.QRect(540, -70, 601, 261))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\704e26aa3f8b06f0c367a25c0874ba4b.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(jarvisui)
        self.label_8.setGeometry(QtCore.QRect(-40, 780, 361, 221))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\SpotlessWelloffAtlanticridleyturtle-max-1mb.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(jarvisui)
        self.label_6.setGeometry(QtCore.QRect(-10, 120, 461, 321))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\MImN.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(jarvisui)
        self.label_9.setGeometry(QtCore.QRect(-30, 410, 541, 361))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\7a517efee6880af7aa39f0aa707281a1.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(jarvisui)
        self.label_10.setGeometry(QtCore.QRect(1200, 30, 331, 251))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\ceb11f58fa11f9b8c151cc3a4ce49b71.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(jarvisui)
        self.label_11.setGeometry(QtCore.QRect(1000, 560, 411, 471))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\giphy (1).gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(jarvisui)
        self.label_12.setGeometry(QtCore.QRect(320, 690, 371, 361))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\06.gif"))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(jarvisui)
        self.label_13.setGeometry(QtCore.QRect(1380, 340, 491, 181))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\normal-heart-rate1.gif"))
        self.label_13.setObjectName("label_13")
        self.pushButton_2 = QtWidgets.QPushButton(jarvisui)
        self.pushButton_2.setGeometry(QtCore.QRect(1720, 980, 141, 61))
        self.pushButton_2.setStyleSheet("border-color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 175, 195, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_14 = QtWidgets.QLabel(jarvisui)
        self.label_14.setGeometry(QtCore.QRect(1530, 560, 351, 91))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\btn3.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(jarvisui)
        self.label_15.setGeometry(QtCore.QRect(1640, 620, 2181, 1231))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\black.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(jarvisui)
        self.label_16.setGeometry(QtCore.QRect(1530, 670, 351, 91))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\btn3.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(jarvisui)
        self.label_17.setGeometry(QtCore.QRect(1530, 790, 351, 91))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\btn3.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(jarvisui)
        self.label_18.setGeometry(QtCore.QRect(1540, 920, 351, 91))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("C:\\Users\\joy\\c programming\\JARVIS\\btn3.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.pushButton = QtWidgets.QPushButton(jarvisui)
        self.pushButton.setGeometry(QtCore.QRect(1650, 810, 121, 41))
        self.pushButton.setStyleSheet("font: 75 8pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Wide Latin\";\n"
"background-color: rgb(0, 96, 144);\n"
"background-color: rgb(21, 122, 153);\n"
"font: 75 18pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(jarvisui)
        self.pushButton_3.setGeometry(QtCore.QRect(1640, 940, 161, 41))
        self.pushButton_3.setStyleSheet("font: 75 8pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Wide Latin\";\n"
"background-color: rgb(0, 96, 144);\n"
"background-color: rgb(21, 122, 153);\n"
"font: 75 18pt \"Segoe UI\";")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(jarvisui)
        QtCore.QMetaObject.connectSlotsByName(jarvisui)

    def retranslateUi(self, jarvisui):
        _translate = QtCore.QCoreApplication.translate
        jarvisui.setWindowTitle(_translate("jarvisui", "MainWindow"))
        #self.pushButton_2.setText(_translate("jarvisui", "FINISH"))
        self.pushButton.setText(_translate("jarvisui", "START"))
        self.pushButton_3.setText(_translate("jarvisui", "TERMINATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisui = QtWidgets.QWidget()
    ui = Ui_jarvisui()
    ui.setupUi(jarvisui)
    jarvisui.show()
    sys.exit(app.exec_())
